### ISSUE TITLE
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 

### ISSUE THREAD

**Issue by Sandy4321** [eug/dynamic-time-warping#1]
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 
	for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ?

**Comment by eug** [comment]
Assuming the categorical values `red,black,green` are labels of your observations, and the remaining values are always continuous, yes. Just make sure your dataset has the same input structure as in the [input folder](https://github.com/eug/dynamic-time-warping/tree/master/input), otherwise, you must write your own dataset reader.

This project is not for general purpose, but it can be easily expanded for other applications. Thus, I recommend you to read the source code to get the idea behind this project and see what fits for you.
